[package]
name = "visualiser"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../crates/common" }
async_impl = { path = "../../crates/async_impl" }
threaded_impl = { path = "../../crates/threaded_impl" }
egui = "0.24"
eframe = { version = "0.24", features = ["default"] }
egui_plot = "0.24"
tokio = { version = "1.0", features = ["full"] }
winapi = { version = "0.3", features = ["winuser", "windef"] }
